### ISSUE TITLE
Enabled GPU-Support under Windows with Faster-Whisper - but I see no difference in speed - how to make sure GPU is enabled?

### ISSUE THREAD

**Issue by svenniuwe** [chidiwilliams/buzz#1071]
Hello,
first question: is the documentation here still valid:
https://github.com/chidiwilliams/buzz/blob/main/CONTRIBUTING.md#gpu-support
or is GPU-Support automatically enabled under Windows?

To check if it gets faster using "Faster-Whisper" I followed the above mentioned steps and enabled GPU support.

But in Test the speed is the same. In Debug-Output I see no mention of Cuda or GPU.

How can I check that I successfully enabled GPU-Support under Windows?

Thank you
Sven

**Comment by raivisdejus** [comment]
@svenniuwe Please use latest development version https://chidiwilliams.github.io/buzz/docs/faq#9-where-can-i-get-latest-development-version 
An issue with enabling GPU for Faster whisper on Windows was fixed since last release. 

Also I assume you have an Nvidia GPU as I think GPUs from other manufacturers will not support GPU acceleration with Faster whisepr.

On AMD you can try the Huggingface whisper type or the regular Whisper. Those may use GPU on non-Nvidia GPUs. Maybe.

**Comment by raivisdejus** [comment]
Will close the issue, but if more assistance is needed feel free to comment below

**Comment by svenniuwe** [comment]
@raivisdejus First: Thank you for all your efforts!
I could finally install/test the latest dev version (1.3.0) but speed is still the same.
Is there any debug log so that I could be sure to run on GPU? 
Yes, I have NVIDIA GPU (RTX 4070 Ti Super) with 16 GB VRAM.
When I use Faster-Whisper from CLI with this project here:
https://github.com/Purfview/whisper-standalone-win/releases/tag/Faster-Whisper-XXL
after a short "warmup time" of maybe 15 seconds, I get even with model large-v2 a speed of 10 seconds transcribed per second. So 10x real time speed. So I do not know how you can handle that "warmup time" in Buzz, so it should be possible to achieve "real time" easily...

**Comment by svenniuwe** [comment]
@raivisdejus Found the LOG-File, it looks like it is indeed still running on my CPU:

[2025-02-10 08:32:40,232] recording_transcriber.start:77 DEBUG -> CUDA version detected: 12.1
[2025-02-10 08:32:40,232] recording_transcriber.start:91 DEBUG -> CUDA GPUs are currently no supported on Running on Windows, using CPU
[2025-02-10 08:32:41,874] recording_transcriber.start:128 DEBUG -> Recording, transcription options = TranscriptionOptions(language='de', task=<Task.TRANSCRIBE: 'transcribe'>, model=TranscriptionModel(), word_level_timings=False, extract_speech=False, temperature=(0.0, 0.2, 0.4, 0.6, 0.8, 1.0), initial_prompt='', openai_access_token='', enable_llm_translation=False, llm_prompt='', llm_model=''), model path = C:\Users\svens\AppData\Local\Buzz\Buzz\Cache\models\models--Systran--faster-whisper-medium\snapshots\08e178d48790749d25932bbc082711ddcfdfbc4f, sample rate = 16000, device = 1
[2025-02-10 08:32:47,389] 

Any hint?

**Comment by raivisdejus** [comment]
@svenniuwe Nice catch! Check the latest development build.

An older guard for Windows was left for live recordings. This was removed for file transcriptions previously and now is also removed for live transcripts.
