### ISSUE TITLE
Error, because of model or buzz?

### ISSUE THREAD

**Issue by githubberina** [chidiwilliams/buzz#862]
![image](https://github.com/user-attachments/assets/51dd84b3-cf87-426c-8e4d-4808f450fc21)

I don't know how to read this, can you help me? Is the issue with the model?

**Comment by githubberina** [comment]
![image](https://github.com/user-attachments/assets/bc8dd070-9f8b-42cc-b37e-f00d18f87e2e)

I also get this with a model I've used previously succesfully with .84 version. The new 1.01 turns on, I start downloading hugging face model (great to have these easily downloadable btw!) but it crashes in couple seconds. I turn on buzz again and it gives me this error when trying to download same model.

**Comment by raivisdejus** [comment]
Please select a language to transcribe, I think this is an issue with "Detect language" that was recently fixed but is not yet released

**Comment by githubberina** [comment]
> Please select a language to transcribe, I think this is an issue with "Detect language" that was recently fixed but is not yet released

I have selected it and set to "Finnish" which is the language of model and my video, but iirc I haven't tried it by not selecting and leaving it on "select language" instead. I might check that option out.

**Comment by githubberina** [comment]
![image](https://github.com/user-attachments/assets/4568eb50-b884-4e72-897f-23dc1e597fb1)

This works in 0.8.4, but doesn't work with 1.0 with same settings, not sure about 0.9. 
The V3 version of said model doesn't work with any version of Buzz.

**Comment by raivisdejus** [comment]
@githubberina I will need to do some investigation on what exactly is missing for this model to work, but I am sure we can make it work in not too distant future

**Comment by raivisdejus** [comment]
@githubberina Let's try the very latest development version of the Buzz from here https://github.com/chidiwilliams/buzz/actions/runs/10170061035/attempts/1 (log into github to see the artifacts section)
Use Faster Whisper with [this custom model](https://huggingface.co/Finnish-NLP/whisper-large-finnish-v3-ct2)
To download custom model you can use Settings -> Models section.

Faster whisper is generally faster and requires less memory than regular whisper

**Comment by githubberina** [comment]
Hello, thank you for trying to solve this issue! 

![image](https://github.com/user-attachments/assets/9a217552-838d-4d6a-8ffc-f5573c02b4f3)

I downloaded the model succesfully with 1.0.2, but it gave an unknown error without a pop-up.

**Comment by raivisdejus** [comment]
@githubberina Paste this in windows address bar `%USERPROFILE%\AppData\Local\Buzz\Buzz\Logs` and see what is in the logs file. You can clear it and then post the output here, relevant part may be not the very last lines, so post here longer part of the log.

Also if previous downloads had some issue on previous version your model may be in a broken state. To rule this out you can try to delete it and download again from Settings -> Models.

I tried to transcribe a file with it on Linux and it worked, so we may be facing some Windows specific issue as well

**Comment by TheTruthisTheWay11** [comment]
I'm running into the same error trying to use this model here: https://huggingface.co/WANGTINGTING/whisper-large-v2-zh-TW. Do you think the issue is specifically related to large language models? When I use other ones, I don't have any problems.

**Comment by raivisdejus** [comment]
@githubberina The `Finnish-NLP/whisper-large-finnish-v3` was fixed on model side. The [generation_config.json](https://huggingface.co/Finnish-NLP/whisper-large-finnish-v3/blob/main/generation_config.json) file was missing from the model. 

For model `Finnish-NLP/whisper-large-v2-finnish` something is not adding up, might be the missing generation config file, might be something else. 

@TheTruthisTheWay11 Please try the latest development version from https://github.com/chidiwilliams/buzz/actions/runs/10211346492
You have to log into the github to see the artifact section your model should work with this version.

**Comment by TheTruthisTheWay11** [comment]
@raivisdejus Unfortunately, I'm still getting the error. 
![BuzzIssue](https://github.com/user-attachments/assets/658d2adb-abb3-4dcb-b22d-9b3615bceba4)

**Comment by TheTruthisTheWay11** [comment]
@raivisdejus Thankfully, I was able to get this version to work: https://huggingface.co/XA9/faster-whisper-large-v2-zh-TW. It's the same repo as the one I posted, just converted to the CTranslate2 format.

**Comment by githubberina** [comment]
I am probably doing something wrong, but I got error without pop-up, using 1.0.2 with these settings:
![image](https://github.com/user-attachments/assets/37a0fb07-03d7-4bdb-bab7-853c9c959337)

**Comment by raivisdejus** [comment]
@githubberina Ensure you have the latest version of `1.0.2`, like get it from here https://github.com/chidiwilliams/buzz/actions/runs/10333865273
Then delete old model folder it's in the cache folder, info on that is here https://chidiwilliams.github.io/buzz/docs/faq 
Then download the model again.

If you still get the error, see the logs file in the Cache directory or run Buzz from command line on Linux or Mac to see the logging output

**Comment by githubberina** [comment]
Thanks, it's working now!! I think it was because of cache folders.
